# Generated by Django 4.2.5 on 2023-10-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_order_count_user_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
