# Generated by Django 4.2.5 on 2023-10-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
