# Generated by Django 4.2.5 on 2023-10-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_mail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
