# Generated by Django 4.2.5 on 2023-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_follow_is_accepted_follow_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.AddField(
            model_name='user',
            name='first_signin_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_signin_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_signin_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_signin_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
