# Generated by Django 4.2.5 on 2023-10-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_payment_cvc_payment_date_payment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Address Model'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Follow Model'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Payment Model'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Model'},
        ),
    ]
