# Generated by Django 4.2.5 on 2023-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_address_options_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.IntegerField(default=0),
        ),
    ]
