# Generated by Django 4.2.5 on 2023-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_approved_status_remove_user_id_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
