# Generated by Django 4.2.5 on 2023-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_payment_bank_name_payment_brand_payment_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login_device',
            new_name='last_signin_device',
        ),
        migrations.AddField(
            model_name='user',
            name='signup_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
