# Generated by Django 4.2.5 on 2023-10-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_orderitem_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.orderdetail'),
        ),
    ]
