# Generated by Django 4.2.5 on 2023-10-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_order_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'OrderDetail Model'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem Model'},
        ),
    ]
