# Generated by Django 4.2.5 on 2023-10-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderdetail_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='status',
            new_name='order_status',
        ),
    ]
