# Generated by Django 4.2.5 on 2023-10-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_status_orderdetail_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'OrderDetail Model'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'OrderItem Model'},
        ),
    ]
