# Generated by Django 4.2.5 on 2023-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderdetail_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='payment',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
