# Generated by Django 4.2.5 on 2023-11-07 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_payment_bank_name_payment_brand_payment_country_and_more'),
        ('orders', '0009_remove_orderdetail_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.payment'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
