# Generated by Django 4.2.5 on 2023-11-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderdetail_arrive_at_orderdetail_stripe_refund_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_invoice_id',
        ),
    ]
