# Generated by Django 4.2.5 on 2023-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderdetail_amount_saved_orderdetail_amount_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='shipping_method',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_method',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
