# Generated by Django 4.2.5 on 2023-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderdetail_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount_shipping',
            field=models.IntegerField(default=0),
        ),
    ]
