# Generated by Django 4.2.5 on 2023-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderdetail_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_method',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_rate',
            field=models.IntegerField(default=0),
        ),
    ]
