# Generated by Django 4.2.5 on 2023-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderitem_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='shipping_method',
            field=models.CharField(blank=True, null=True),
        ),
    ]
