# Generated by Django 4.2.5 on 2023-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_rename_shipping_method_orderdetail_shipping_service_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='shipping_method',
            new_name='shipping_service_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_service_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
