# Generated by Django 4.2.5 on 2023-10-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
