# Generated by Django 4.2.5 on 2023-11-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_like_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipping', serialize=False, to='products.variant')),
                ('dimension', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.CharField(blank=True, max_length=500, null=True)),
                ('usa_rate', models.IntegerField(blank=True, null=True)),
                ('global_rate', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Shipping Model',
                'ordering': ['-created_at'],
            },
        ),
    ]
