# Generated by Django 4.2.5 on 2023-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='unit_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='unit_w',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
