# Generated by Django 4.2.5 on 2023-11-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_shipping_unit_d_shipping_unit_w'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='global_rate',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='usa_rate',
        ),
    ]
