# Generated by Django 4.2.5 on 2023-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_metadata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
